### PR TITLE
WIP: Quick fix replace old organization links

### PR DESCRIPTION
**Pull request by phyro**
Don't merge. I'm checking what's up with the CI. There's a bunch of things in the project I don't know what they are about and should be checked, likely will need a lot of help here.
cc: @splix @tzdybal @whilei @realcodywburns and whoever knows the code base of this

I'm also fine if you guys close this and open a new PR if you have time and can do it faster :+1:

TODO:
- [ ] Check if the thing builds and works
- [ ] Check the CI config, bats and other changes
- [ ] Make sure it still works on all the systems
- [ ] Check if it makes sense to rebuild the easyjson thing `manager_easyjson.go`
- [ ] Replace vendor/github.com/ethereumproject with ethereumclassic?
- [ ] Make new .lock files?
- [ ] A bunch of other things
- [x] Check if changing link of setup.py of ethash ruins something (It doesn't make it worse, the link wasn't working before, likely died when it was changed from ethereum since that one still works) 

This is addressing the https://github.com/ethereumclassic/go-ethereum/issues/1

### CODE REVIEW

**Comment by realcodywburns** [comment]
adding ci to checks and wip bot

**Comment by whilei** [comment]
I think the CI migration should be moved to it's own concern; this repo won't have the keys for the normal distribution pipeline (fatally broken), and we'll need to establish a new archive/distribution storage endpoint for builds. 

That would leave this issue for now focusing on 
- making sure things work when building from source, eg. `make *`
  + vendored dep and `dep` files (toml and lock)
    + https://github.com/ETCDEVTeam/sputnikvm-ffi/pull/14
  + scripts/
- getting documentation (eg. `md`) files to say the right things

**Comment by whilei** [comment]
@phyro See https://github.com/phyro/go-ethereum/pull/1 w/r/t easyjson in accounts/. It would be better if this were a standard part of CI or make processes, but I guess this should work for now.

**Comment by realcodywburns** [comment]
creating a general ci repo for ci/cd pipeline planning as well github.com/ethereumclassic/devops

**Comment by phyro** [comment]
@whilei thanks for the PR! I was discussing this with @tzdybal and he agreed to take over this PR (I lack the understanding of the project and familiarity with `go`). I'm not sure how much time he has now though because he got a new job. @tzdybal are you still on this one?

**Comment by tzdybal** [comment]
Status is following - we need `ethash` build to be able to build `go-ethereum`. I'm working on Windows build to pass AppVeyor, to be able to merge PR in `ethash`. After that I can make the PR in this repo. 
All other dependencies (sputnikvm-ffi, benchmark) are ready.

Unfortunately fixing AppVeyor build is slow and painful process.

**Comment by whilei** [comment]
Thanks @phyro and @tzdybal. @phyro if you'll please (assuming @tzdybal agrees) reopen this PR with a target branch at this repo instead of your fork, then we can push right to that "upstream branch" instead of jumping through the [PR's on PR's](https://github.com/phyro/go-ethereum/pull/1) hoops ;)

**Comment by whilei** [comment]
And to your second point, @phyro, (about sed's implications) you're right to raise the concern. Theoretically the changes should largely impact only package, dependency, and URL paths, but absolutely worth doing a real close-read review before merging.

**Comment by phyro** [comment]
Closing in favor of https://github.com/ethereumclassic/go-ethereum/pull/6

**Pull request closed without merging**
