### PR TITLE
Fix/replace old organization links (extends #6)

### PR DESCRIPTION
**Pull request by whilei**
This is just an 'extension' PR from @phyro 's #6 since I don't have permissions to push to upstream branches. 

Progress above #6 includes fixing a generated file for `mailru/easyjson` in accounts/manager.go and getting a start on setting up [AppVeyor->Bintray and Travis->Bintray distribution channels](https://github.com/ethereumclassic/DevOps#bintray). (The CI configs are a start, but knowing how CI setups usually go, they'll probably need some further revisions. And [the Travis one-enormous-script](https://github.com/ethereumclassic/go-ethereum/compare/fix/replace-old-organization-links...whilei:fix/replace-old-organization-links?expand=1#diff-354f30a63fb0907d4ad57269548329e3R15) is really ugly - it should be "yaml-fied" - this is just an early hybrid of [an old ethereumproject/go-ethereum .travis.yml](https://github.com/ethereumclassic/go-ethereum/blob/d0b885516ead6e46f084cc60e4298997b2a8b196/.travis.yml) and [the current .circleci/config.yml](https://github.com/ethereumclassic/go-ethereum/blob/master/.circleci/config.yml).)

@realcodywburns There are a few places we'll need your administration here - both AppVeyor and Travis need `key.secret`s to be configured for Bintray deploys, and it looks like you'll need to set up a 'Package' named `go-ethereum` on https://bintray.com/ethereumclassic/Go-ethereum because [the Bintray deploy docs](https://www.appveyor.com/docs/deployment/bintray/) say they'll fail without that pre-existing.

### CODE REVIEW

**Comment by whilei** [comment]
@tzdybal PTAL, as our CircleCI chef, I'm curious if you think we'll even need or want Travis here at all (I mostly stuck back in as "quick-fix" ahead of setting up CircleCI/"Artifactory" stuff), and if things look OK to you otherwise.

**Comment by tzdybal** [comment]
From my research, it seems that we need to use `jfrog-cli` manually to deploy artifacts from CircleCI.
See: https://circleci.com/docs/2.0/artifactory/

**Comment by tzdybal** [comment]
Actually, CircleCI can store build artifacts for us. Same for AppVeyor. On the other hand, it seems nice to have one place to keep them all.

P.S. Just found that [AppVeyor keeps artifacts only for 6 months](https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy), so this is another argument to use something else.

**Comment by realcodywburns** [comment]
package has been added and looking into keys.secret

**Pull request closed without merging**
